-- Create table for raw Milenium telemetry data
create table if not exists public.milenium_telemetry (
    id uuid not null default gen_random_uuid(),
    created_at timestamp with time zone not null default now(),
    
    -- Telemetry payload
    filename text not null,          -- The .txt filename generated by the spooler
    raw_content text not null,       -- The exact string content intercepted from the printer
    agent_version text default '1.0', -- Version of the python sidecar
    
    -- Status tracking (for later if we process it)
    status text not null default 'PENDING', -- PENDING, PROCESSED, ERROR, IGNORED
    processed_at timestamp with time zone,
    
    constraint milenium_telemetry_pkey primary key (id)
);

-- Note: We intentionally do NOT enable RLS so the Python agent can use the 
-- service_role key OR anon key to push data without auth complication for now,
-- OR we enable RLS but allow anonymous inserts for the telemetry endpoint.

-- Let's enable RLS and create a policy for anonymous inserts
alter table public.milenium_telemetry enable row level security;

-- Allow anyone (the python agent using ANON key) to insert telemetry data
create policy "Enable insert for python agent"
on public.milenium_telemetry for insert
with check (true);

-- Allow authenticated users (admin dashboard) to read the telemetry
create policy "Enable read access for authenticated users"
on public.milenium_telemetry for select
to authenticated
using (true);
